Pin oslo.db for python3
With the newer package of oslo.db (11.0.0), running the DB migration
results in the following exception:

    TypeError: 'int' object is not iterable

Pin oslo.db for now, until we can find out why the newer version
breaks it.